# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: fetchData

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  
  schedule:
    - cron: '0 0 * * *'
  watch:
    types: [started]
env:
  TZ: Asia/Shanghai
jobs:
  change-and-push:
    runs-on: ubuntu-latest
    env:
      ALDICOOKIE: ${{ secrets.ALDICOOKIE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        # env:
        #   PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: 18.x
      - name: npm install
        run: |
          npm install
      - name: "运行 啤酒信息"
        run: 
          node index.js       
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GIT_TOKEN }}"
          add_timestamp: false
          commit_prefix: "[AUTO]"
          commit_message: "Automatic commit"
          force: false
